// Generated by GraphWalker (http://www.graphwalker.org)
package testautomation;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "testautomation/VVSMusic.graphml")
public interface VVSMusic {

    @Edge()
    void e_token_expired();

    @Edge()
    void e_search_song_with_token();

    @Edge()
    void e_search_song();

    @Edge()
    void e_get_songs_with_publicity();

    @Edge()
    void e_get_songs();

    @Edge()
    void e_start_the_program();

    @Edge()
    void e_get_token();

    @Vertex()
    void v_SearchWithoutToken();

    @Vertex()
    void v_SearchWithToken();

    @Vertex()
    void v_LoggedIn();

    @Vertex()
    void Ready();
}
